export class Staff {
  address: string;
  // address2
  // bankname
  // bloodtype
  // cardnumber
  // cellphone
  // citizenshipcode
  // counter
  // countersalary
  // dateapply
  // datebirth
  // datemedical
  // daterange
  // dateregisterinsurance
  // department1
  // department2
  // department3
  // department4
  // department5
  // department6
  // departmentsys
  // domicile
  // educationallevel
  // email
  // ethniccode
  // female
  // firstname
  // healthcode
  // height
  // idcode
  // isfederation
  // isforeigner
  // isleader
  // isparttime
  // istablets
  // isuniontists
  // jobtitlecode
  // lastname
  // name2
  // nationalcode
  // numberbank
  // numberinsurance
  // numbermedical
  // phonenumber
  // placeborn
  // placeidcode
  // placemedical
  // provincecode
  // provincecode2
  // regencycode
  // registerhospital
  // religioncode
  // skillwork
  // stafftype
  // thumb
  // trydate
  // usercode
  // veterans
  // viillage
  // viillage2
  // wards
  // wards2
  // weight
  constructor(address: string) {
    this.address = ''
  }
}
